project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: Christiana's Final Project
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: aboutme/aboutme-index.qmd
        text: About me
        
      - href: finalproject/iframe3-index.qmd
        text: Final Project 
        
      - href: myacademicjourney/myacademicjourney-index.qmd
        text: Academic Journey    
        
      - href: publication/publication.qmd
        text: Publication      
        
      - href: sentimentanalysis/sentimentanalysis-index.qmd
        text: Sentiment Analysis
        
      - href: SA2/SA2-index.qmd
        text: SA Results
    
      - href: topicmodeling/topic-index.qmd
        text: Topic Modeling
        
      - href: wordclouds/wordclouds-index.qmd
        text: Wordclouds
        
    logo: images/logo_tepak.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
